name: my firs workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyJobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: File this repository
        run: | 
          echo "Repository ${{ github.repository }} conetd files:"
          tree
      
